### PR TITLE
Add aria-label to covid-hub navigation

### PR DESCRIPTION
**Pull request by the-nathan-smith**
## Description
Add aria-label to covid-hub navigation on SonarCloud recommendation. [TM-2949](https://nhsd-jira.digital.nhs.uk/browse/TM-2949)
## Checklist

- [ ] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] CHANGELOG entry

### CODE REVIEW

**Review by roshaanbajwa — APPROVED** [review]
lgtm

**Comment by diana-nita** [comment]
Don't we need to update the ChangeLog?

**Comment by the-nathan-smith** [comment]
@diana-nita good point, probably should for this change, will do now.

**Review by mayank1211 — APPROVED** [review]
LGTM

**Pull request merged**
