### PR TITLE
Enable adding of custom per template styles

### PR DESCRIPTION
**Pull request by magicaljellybeans**
## Description

Solves #188 by allowing the addition of per template styles.

Custom styles can now be added to the top of templates like this:
```
{% block customStyles %}
  <STYLE type="text/css">
    body { background-color: pink; }
  </STYLE>
{% endblock %}
```

## Checklist

- [x] Tested against our [testing policy](https://github.com/nhsuk/nhsuk-frontend/blob/master/docs/contributing/testing.md) (Resolution, Browser & Accessibility)
- [x] CHANGELOG entry

### CODE REVIEW

**Comment by chrimesdev** [comment]
This looks good, just a few minor things for house keeping;

We need to bump the package version number in `package.json` and the `package-lock.json` files (4.6.0) and replace the CHANGELOG title "Latest" with the current version number v4.6.0 and the date of release

**Comment by chrimesdev** [comment]
Does this make change make https://github.com/nhsuk/nhsuk-prototype-kit/pull/190 redundant now? This change feels like a better approach

**Comment by magicaljellybeans** [comment]
> This looks good, just a few minor things for house keeping;
> 
> We need to bump the package version number in `package.json` and the `package-lock.json` files (4.6.0) and replace the CHANGELOG title "Latest" with the current version number v4.6.0 and the date of release

Do I just put TBC for the date of release or are we just releasing this change now?

**Comment by chrimesdev** [comment]
> > This looks good, just a few minor things for house keeping;
> > We need to bump the package version number in `package.json` and the `package-lock.json` files (4.6.0) and replace the CHANGELOG title "Latest" with the current version number v4.6.0 and the date of release
> 
> Do I just put TBC for the date of release or are we just releasing this change now?

We might aswell release it today

**Review by chrimesdev — APPROVED** [review]

**Pull request merged**
